-- Script para agregar el campo ESTADO_DESCRIPCION a la tabla FACTURAS
-- Ejecutar en Oracle Database

-- Agregar columna ESTADO_DESCRIPCION
ALTER TABLE FACTURAS ADD ESTADO_DESCRIPCION VARCHAR2(100);

-- Comentario para la nueva columna
COMMENT ON COLUMN FACTURAS.ESTADO_DESCRIPCION IS 'Descripción del estado de la factura según códigos del SAT';

-- Actualizar registros existentes con descripciones por defecto
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'POR TIMBRAR' WHERE ESTADO = '66' OR ESTADO IS NULL;
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'EMITIDA' WHERE ESTADO = '0';
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'EN PROCESO DE CANCELACION' WHERE ESTADO = '1';
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'CANCELADA EN SAT' WHERE ESTADO = '2';
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'DE PASO' WHERE ESTADO = '3';
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'EN PROCESO DE EMISION' WHERE ESTADO = '4';
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'FACTURA TEMPORAL' WHERE ESTADO = '99';
UPDATE FACTURAS SET ESTADO_DESCRIPCION = 'EN ESPERA DE CANCELACION BOLETA QUE SUSTITUYE' WHERE ESTADO = '67';

-- Hacer la columna NOT NULL después de actualizar
ALTER TABLE FACTURAS MODIFY ESTADO_DESCRIPCION NOT NULL;

-- Crear índice para mejorar consultas por estado
CREATE INDEX IDX_FACTURAS_ESTADO ON FACTURAS(ESTADO, ESTADO_DESCRIPCION);

-- Verificar la estructura actualizada
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COMMENTS 
FROM USER_COL_COMMENTS 
WHERE TABLE_NAME = 'FACTURAS' 
ORDER BY COLUMN_NAME;

-- Mostrar algunos registros de ejemplo
SELECT UUID, ESTADO, ESTADO_DESCRIPCION, FECHA_GENERACION 
FROM FACTURAS 
ORDER BY FECHA_GENERACION DESC 
FETCH FIRST 10 ROWS ONLY;
