-- Script ALTER TABLE simplificado para MENU_CONFIG
-- Ejecutar línea por línea y omitir las que ya existen

-- Agregar columnas (ejecutar solo si no existen)
-- Si la columna ya existe, ignorar el error ORA-01430

ALTER TABLE MENU_CONFIG ADD FECHA_CREACION DATE DEFAULT SYSDATE;
ALTER TABLE MENU_CONFIG ADD FECHA_MODIFICACION DATE DEFAULT SYSDATE;
ALTER TABLE MENU_CONFIG ADD USUARIO_CREACION VARCHAR2(50) DEFAULT 'SYSTEM';
ALTER TABLE MENU_CONFIG ADD USUARIO_MODIFICACION VARCHAR2(50) DEFAULT 'SYSTEM';

-- Modificar columnas para asegurar valores por defecto
ALTER TABLE MENU_CONFIG MODIFY (FECHA_CREACION DEFAULT SYSDATE);
ALTER TABLE MENU_CONFIG MODIFY (FECHA_MODIFICACION DEFAULT SYSDATE);
ALTER TABLE MENU_CONFIG MODIFY (USUARIO_CREACION DEFAULT 'SYSTEM');
ALTER TABLE MENU_CONFIG MODIFY (USUARIO_MODIFICACION DEFAULT 'SYSTEM');
ALTER TABLE MENU_CONFIG MODIFY (IS_VISIBLE DEFAULT 1);
ALTER TABLE MENU_CONFIG MODIFY (ORDEN DEFAULT 1);

-- Crear índices (si no existen, ignorar error ORA-00955)
CREATE INDEX IDX_MENU_CONFIG_PERFIL ON MENU_CONFIG(ID_PERFIL);
CREATE INDEX IDX_MENU_CONFIG_ORDEN ON MENU_CONFIG(ID_PERFIL, ORDEN);

-- Agregar constraint de foreign key (si no existe, ignorar error ORA-02275)
ALTER TABLE MENU_CONFIG ADD CONSTRAINT FK_MENU_CONFIG_PERFIL 
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL);

-- Agregar comentarios
COMMENT ON TABLE MENU_CONFIG IS 'Configuración de visibilidad de menús por perfil de usuario';
COMMENT ON COLUMN MENU_CONFIG.ID_CONFIG IS 'Identificador único de la configuración';
COMMENT ON COLUMN MENU_CONFIG.ID_PERFIL IS 'Identificador del perfil de usuario';
COMMENT ON COLUMN MENU_CONFIG.MENU_LABEL IS 'Etiqueta/nombre del menú o pantalla';
COMMENT ON COLUMN MENU_CONFIG.MENU_PATH IS 'Ruta del menú (NULL para pestañas principales)';
COMMENT ON COLUMN MENU_CONFIG.IS_VISIBLE IS 'Indica si el menú es visible (1) u oculto (0)';
COMMENT ON COLUMN MENU_CONFIG.ORDEN IS 'Orden de visualización del menú';
COMMENT ON COLUMN MENU_CONFIG.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN MENU_CONFIG.FECHA_MODIFICACION IS 'Fecha de última modificación';
COMMENT ON COLUMN MENU_CONFIG.USUARIO_CREACION IS 'Usuario que creó el registro';
COMMENT ON COLUMN MENU_CONFIG.USUARIO_MODIFICACION IS 'Usuario que realizó la última modificación';

