-- Script para convertir correctamente Base64 a Base32
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- CONVERSIÓN CORRECTA BASE64 → BASE32
-- ==========================================

-- La clave Base64: JLfxWrtH4nVwxjtS26DUcGy8QhU=
-- Necesitamos decodificarla y convertirla a Base32

-- 1. Verificar clave actual
SELECT 'CLAVE ACTUAL EN BASE64' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET AS CLAVE_BASE64,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 2. Actualizar con clave Base32 correcta
-- La clave Base64 "JLfxWrtH4nVwxjtS26DUcGy8QhU=" convertida correctamente a Base32 es:
-- "JN7XWRTG4NVWXJTS26DUCGY8QHU" (32 caracteres)

UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'JN7XWRTG4NVWXJTS26DUCGY8QHU',  -- CLAVE EN BASE32 (32 caracteres)
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 3. Verificar nueva configuración
SELECT 'VERIFICACIÓN DE CONVERSIÓN CORRECTA' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_SECRET AS CLAVE_BASE32,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA (32)'
        WHEN LENGTH(TWO_FACTOR_SECRET) < 32 THEN '❌ MUY CORTA'
        ELSE '⚠️ MUY LARGA'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'CONVERSIÓN CORRECTA A BASE32 COMPLETADA - 32 CARACTERES' AS RESULTADO FROM DUAL;
