-- Script de restauración de acceso usando configuración actual
-- Este script NO agrega nuevas funcionalidades, solo restaura el acceso

-- 1. Verificar usuarios activos actuales
SELECT 'USUARIOS ACTIVOS ACTUALES' AS RESTAURACION FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    PASSWORD
FROM USUARIOS
WHERE ESTATUS_USUARIO = 'A'
ORDER BY NO_USUARIO;

-- 2. Crear usuario de emergencia si no existe ninguno activo
INSERT INTO USUARIOS (
    NO_USUARIO, NOMBRE_EMPLEADO, PASSWORD, ESTATUS_USUARIO, ID_PERFIL, 
    FECHA_ALTA, FECHA_MOD, USUARIO_MOD, ID_DFI, ID_ESTACIONAMIENTO, 
    MODIFICA_UBICACION
)
SELECT 
    'EMERGENCIA', 'Usuario de Emergencia', 'emergencia123', 'A', 
    (SELECT MIN(ID_PERFIL) FROM PERFIL WHERE STATUS_PERFIL = 'A'),
    SYSDATE, SYSDATE, 'SYSTEM', 1, 1, 'N'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM USUARIOS WHERE ESTATUS_USUARIO = 'A'
);

COMMIT;

-- 3. Asegurar que al menos un usuario tenga acceso
UPDATE USUARIOS 
SET ESTATUS_USUARIO = 'A'
WHERE NO_USUARIO = (
    SELECT NO_USUARIO FROM (
        SELECT NO_USUARIO FROM USUARIOS 
        ORDER BY CASE WHEN NO_USUARIO = 'ADMIN' THEN 1 ELSE 2 END
    ) WHERE ROWNUM = 1
);

COMMIT;

-- 4. Verificar perfiles disponibles
SELECT 'PERFILES DISPONIBLES' AS RESTAURACION FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL,
    STATUS_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 5. Crear perfil de emergencia si no existe ninguno
INSERT INTO PERFIL (
    ID_PERFIL, NOMBRE_PERFIL, STATUS_PERFIL, DESCRIPCION_PERFIL,
    FECHA_ALTA, FECHA_MOD, USUARIO_MOD
)
SELECT 
    999, 'EMERGENCIA', 'A', 'Perfil de emergencia para acceso',
    SYSDATE, SYSDATE, 'SYSTEM'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM PERFIL WHERE STATUS_PERFIL = 'A'
);

COMMIT;

-- 6. Asignar perfil de emergencia a usuarios sin perfil
UPDATE USUARIOS 
SET ID_PERFIL = 999
WHERE ID_PERFIL IS NULL 
AND ESTATUS_USUARIO = 'A';

COMMIT;

-- 7. Verificar estado final
SELECT 'ESTADO FINAL DESPUÉS DE RESTAURACIÓN' AS RESTAURACION FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ESTATUS_USUARIO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL,
    'ACCESO RESTAURADO' AS ESTADO
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
WHERE u.ESTATUS_USUARIO = 'A'
ORDER BY u.NO_USUARIO;

-- 8. Mostrar credenciales de acceso
SELECT 'CREDENCIALES DE ACCESO DISPONIBLES' AS RESTAURACION FROM DUAL;
SELECT 
    NO_USUARIO AS USUARIO,
    PASSWORD AS CONTRASEÑA,
    NOMBRE_EMPLEADO AS NOMBRE,
    'USAR ESTAS CREDENCIALES' AS INSTRUCCION
FROM USUARIOS
WHERE ESTATUS_USUARIO = 'A'
ORDER BY CASE WHEN NO_USUARIO = 'EMERGENCIA' THEN 1 ELSE 2 END;

-- Script completado
SELECT 'ACCESO RESTAURADO USANDO CONFIGURACIÓN ACTUAL' AS RESULTADO FROM DUAL;
