-- Script de diagnóstico para verificar el estado del sistema de autenticación
-- Ejecutar en Oracle Database

-- 1. Verificar estructura de la tabla USUARIOS
SELECT 'ESTRUCTURA TABLA USUARIOS' AS DIAGNOSTICO FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
ORDER BY COLUMN_ID;

-- 2. Verificar usuarios existentes
SELECT 'USUARIOS EXISTENTES' AS DIAGNOSTICO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    USER_ROLE,
    PASSWORD_ENCODED,
    TWO_FACTOR_ENABLED,
    LAST_LOGIN
FROM USUARIOS
ORDER BY NO_USUARIO;

-- 3. Verificar tabla de estados de pago
SELECT 'ESTADOS DE PAGO' AS DIAGNOSTICO FROM DUAL;
SELECT 
    NO_USUARIO,
    PAYMENT_STATUS,
    LAST_PAYMENT_DATE,
    CREATED_AT
FROM USER_PAYMENT_STATUS
ORDER BY NO_USUARIO;

-- 4. Verificar perfiles disponibles
SELECT 'PERFILES DISPONIBLES' AS DIAGNOSTICO FROM DUAL;
SELECT ID_PERFIL, NOMBRE_PERFIL, STATUS_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 5. Probar función de acceso
SELECT 'PRUEBA FUNCIÓN DE ACCESO' AS DIAGNOSTICO FROM DUAL;
SELECT 
    NO_USUARIO,
    FN_USER_HAS_ACCESS(NO_USUARIO) AS TIENE_ACCESO
FROM USUARIOS
WHERE ESTATUS_USUARIO = 'A';

-- 6. Verificar contraseñas (solo mostrar longitud por seguridad)
SELECT 'ESTADO DE CONTRASEÑAS' AS DIAGNOSTICO FROM DUAL;
SELECT 
    NO_USUARIO,
    LENGTH(PASSWORD) AS LONGITUD_PASSWORD,
    PASSWORD_ENCODED,
    CASE 
        WHEN PASSWORD_ENCODED = 'Y' THEN 'Codificada'
        ELSE 'Sin codificar'
    END AS ESTADO_CONTRASEÑA
FROM USUARIOS
ORDER BY NO_USUARIO;

-- 7. Verificar índices creados
SELECT 'ÍNDICES CREADOS' AS DIAGNOSTICO FROM DUAL;
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN ('USUARIOS', 'USER_PAYMENT_STATUS')
ORDER BY TABLE_NAME, INDEX_NAME;

-- 8. Verificar triggers
SELECT 'TRIGGERS CREADOS' AS DIAGNOSTICO FROM DUAL;
SELECT TRIGGER_NAME, TABLE_NAME, STATUS
FROM USER_TRIGGERS
WHERE TABLE_NAME = 'USER_PAYMENT_STATUS';

-- Script completado
SELECT 'DIAGNÓSTICO COMPLETADO' AS RESULTADO FROM DUAL;
