-- Script para corregir el tipo de datos de la columna TWO_FACTOR_SECRET
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- CORRECCIÓN DE TIPO DE DATOS
-- ==========================================

-- 1. Verificar el tipo actual de la columna
SELECT 'VERIFICAR TIPO DE COLUMNA' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    CHAR_USED,
    NULLABLE
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
AND COLUMN_NAME = 'TWO_FACTOR_SECRET';

-- 2. Verificar si hay datos en la columna
SELECT 'VERIFICAR DATOS ACTUALES' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    CASE 
        WHEN TWO_FACTOR_SECRET IS NULL THEN 'NULL'
        ELSE 'TIENE DATOS'
    END AS ESTADO_CLAVE,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 3. Crear columna temporal con tipo correcto
ALTER TABLE USUARIOS ADD TWO_FACTOR_SECRET_TEMP VARCHAR2(50);

-- 4. Copiar datos a la columna temporal (si existen)
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET_TEMP = TWO_FACTOR_SECRET
WHERE NO_USUARIO = 'admin'
AND TWO_FACTOR_SECRET IS NOT NULL;

-- 5. Eliminar la columna problemática
ALTER TABLE USUARIOS DROP COLUMN TWO_FACTOR_SECRET;

-- 6. Crear la columna con el tipo correcto
ALTER TABLE USUARIOS ADD TWO_FACTOR_SECRET VARCHAR2(50);

-- 7. Copiar datos de vuelta
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = TWO_FACTOR_SECRET_TEMP
WHERE NO_USUARIO = 'admin'
AND TWO_FACTOR_SECRET_TEMP IS NOT NULL;

-- 8. Eliminar columna temporal
ALTER TABLE USUARIOS DROP COLUMN TWO_FACTOR_SECRET_TEMP;

-- 9. Insertar clave correcta
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin';

-- 10. Verificación final
SELECT 'VERIFICACIÓN FINAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA (32)'
        ELSE '❌ LONGITUD INCORRECTA (' || LENGTH(TWO_FACTOR_SECRET) || ')'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 11. Verificar el tipo de columna corregido
SELECT 'VERIFICAR TIPO CORREGIDO' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    CHAR_USED,
    NULLABLE
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
AND COLUMN_NAME = 'TWO_FACTOR_SECRET';

COMMIT;

-- Script completado
SELECT 'CORRECCIÓN DE TIPO DE DATOS COMPLETADA' AS RESULTADO FROM DUAL;
