-- Script para verificar usuarios existentes y sus contraseñas
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR USUARIOS Y CONTRASEÑAS
-- ==========================================

-- 1. Verificar usuarios existentes
SELECT 'USUARIOS EXISTENTES' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    LENGTH(PASSWORD) AS LONGITUD_PASSWORD,
    CASE 
        WHEN PASSWORD_ENCODED IS NULL THEN 'SIN CODIFICAR'
        ELSE PASSWORD_ENCODED
    END AS ESTADO_CONTRASEÑA
FROM USUARIOS
ORDER BY NO_USUARIO;

-- 2. Verificar perfiles
SELECT 'PERFILES EXISTENTES' AS INFO FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 3. Verificar relación usuarios-perfiles
SELECT 'USUARIOS Y SUS PERFILES' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ESTATUS_USUARIO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
ORDER BY u.NO_USUARIO;

-- 4. Verificar contraseñas específicas (solo mostrar si son texto plano)
SELECT 'CONTRASEÑAS DE USUARIOS PRINCIPALES' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    CASE 
        WHEN PASSWORD_ENCODED = 'N' OR PASSWORD_ENCODED IS NULL THEN PASSWORD
        ELSE '[CODIFICADA]'
    END AS CONTRASEÑA_VISIBLE,
    CASE 
        WHEN PASSWORD_ENCODED = 'N' OR PASSWORD_ENCODED IS NULL THEN 'TEXTO_PLANO'
        ELSE 'CODIFICADA'
    END AS TIPO_CONTRASEÑA
FROM USUARIOS
WHERE NO_USUARIO IN ('admin', 'jefe', 'operador', 'SUPERADMIN')
ORDER BY NO_USUARIO;

-- Script completado
SELECT 'VERIFICACIÓN COMPLETADA' AS RESULTADO FROM DUAL;
