-- Script para verificar jerarquía de roles y privilegios
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR JERARQUÍA DE ROLES
-- ==========================================

-- 1. Mostrar todos los usuarios con sus roles y perfiles
SELECT 'JERARQUÍA DE USUARIOS Y ROLES' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL,
    u.USER_ROLE,
    CASE 
        WHEN u.USER_ROLE = 'SUPER_ADMIN' THEN 'NIVEL 1 - CONTROL TOTAL'
        WHEN u.USER_ROLE = 'ADMINISTRADOR' THEN 'NIVEL 2 - ADMINISTRACIÓN'
        WHEN u.USER_ROLE = 'OPERADOR' THEN 'NIVEL 3 - OPERACIÓN'
        WHEN u.USER_ROLE = 'USER' THEN 'NIVEL 4 - USUARIO BÁSICO'
        ELSE 'SIN ROL DEFINIDO'
    END AS NIVEL_PRIVILEGIO,
    ups.PAYMENT_STATUS,
    FN_USER_HAS_ACCESS(u.NO_USUARIO) AS TIENE_ACCESO
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
LEFT JOIN USER_PAYMENT_STATUS ups ON u.NO_USUARIO = ups.NO_USUARIO
WHERE u.ESTATUS_USUARIO = 'A'
ORDER BY 
    CASE u.USER_ROLE 
        WHEN 'SUPER_ADMIN' THEN 1
        WHEN 'ADMINISTRADOR' THEN 2
        WHEN 'OPERADOR' THEN 3
        WHEN 'USER' THEN 4
        ELSE 5
    END,
    u.NO_USUARIO;

-- 2. Verificar privilegios específicos
SELECT 'VERIFICACIÓN DE PRIVILEGIOS' AS INFO FROM DUAL;
SELECT 
    'SUPERADMIN' AS USUARIO,
    CASE 
        WHEN FN_USER_HAS_ACCESS('SUPERADMIN') = 'Y' THEN '✅ TIENE ACCESO'
        ELSE '❌ SIN ACCESO'
    END AS ESTADO_ACCESO,
    'CONTROL TOTAL DEL SISTEMA' AS PRIVILEGIOS
FROM DUAL
UNION ALL
SELECT 
    'admin' AS USUARIO,
    CASE 
        WHEN FN_USER_HAS_ACCESS('admin') = 'Y' THEN '✅ TIENE ACCESO'
        ELSE '❌ SIN ACCESO'
    END AS ESTADO_ACCESO,
    'ADMINISTRACIÓN DEL SISTEMA' AS PRIVILEGIOS
FROM DUAL
UNION ALL
SELECT 
    'jefe' AS USUARIO,
    CASE 
        WHEN FN_USER_HAS_ACCESS('jefe') = 'Y' THEN '✅ TIENE ACCESO'
        ELSE '❌ SIN ACCESO'
    END AS ESTADO_ACCESO,
    'ADMINISTRACIÓN DE CRÉDITO' AS PRIVILEGIOS
FROM DUAL
UNION ALL
SELECT 
    'operador' AS USUARIO,
    CASE 
        WHEN FN_USER_HAS_ACCESS('operador') = 'Y' THEN '✅ TIENE ACCESO'
        ELSE '❌ SIN ACCESO'
    END AS ESTADO_ACCESO,
    'OPERACIÓN DE CRÉDITO' AS PRIVILEGIOS
FROM DUAL;

-- 3. Verificar perfiles y sus IDs
SELECT 'PERFILES Y SUS IDs' AS INFO FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL,
    CASE 
        WHEN ID_PERFIL = 99 THEN 'SUPER ADMINISTRADOR'
        WHEN ID_PERFIL = 3 THEN 'ADMINISTRADOR'
        WHEN ID_PERFIL = 2 THEN 'JEFE DE CRÉDITO'
        WHEN ID_PERFIL = 1 THEN 'OPERADOR DE CRÉDITO'
        ELSE 'OTRO PERFIL'
    END AS DESCRIPCION_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 4. Verificar contraseñas de usuarios restaurados
SELECT 'CONTRASEÑAS DE USUARIOS RESTAURADOS' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    PASSWORD,
    CASE 
        WHEN PASSWORD_ENCODED = 'N' THEN 'TEXTO PLANO'
        WHEN PASSWORD_ENCODED = 'Y' THEN 'CODIFICADA'
        ELSE 'DESCONOCIDO'
    END AS TIPO_CONTRASEÑA
FROM USUARIOS
WHERE NO_USUARIO IN ('SUPERADMIN', 'admin', 'jefe', 'operador')
ORDER BY NO_USUARIO;

-- Script completado
SELECT 'VERIFICACIÓN DE JERARQUÍA COMPLETADA' AS RESULTADO FROM DUAL;
