-- Script para forzar la clave correcta y verificar qué está pasando
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- FORZAR CLAVE CORRECTA Y DIAGNOSTICAR
-- ==========================================

-- 1. Verificar qué hay realmente en la columna
SELECT 'ANÁLISIS DETALLADO DE LA COLUMNA' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    LENGTHB(TWO_FACTOR_SECRET) AS BYTES,
    DUMP(TWO_FACTOR_SECRET) AS DUMP_INFO,
    ASCII(SUBSTR(TWO_FACTOR_SECRET, 1, 1)) AS PRIMER_CARACTER_ASCII,
    ASCII(SUBSTR(TWO_FACTOR_SECRET, -1, 1)) AS ULTIMO_CARACTER_ASCII
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 2. Eliminar completamente y recrear
DELETE FROM USUARIOS WHERE NO_USUARIO = 'admin' AND ESTATUS_USUARIO = 'A';

-- 3. Reinsertar usuario con clave correcta
INSERT INTO USUARIOS (
    NO_USUARIO, 
    NOMBRE_EMPLEADO, 
    PASSWORD, 
    ID_PERFIL, 
    ESTATUS_USUARIO,
    TWO_FACTOR_SECRET,
    TWO_FACTOR_ENABLED
) VALUES (
    'admin',
    'Administrador Sistema Y',
    'admin',  -- Password en texto plano para testing
    3,        -- ID_PERFIL para Administrador
    'A',      -- ESTATUS_USUARIO activo
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',  -- Clave Base32 de 32 caracteres
    'N'       -- TWO_FACTOR_ENABLED = N (pendiente de activar)
);

-- 4. Verificación inmediata
SELECT 'VERIFICACIÓN INMEDIATA POST-INSERCIÓN' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    LENGTHB(TWO_FACTOR_SECRET) AS BYTES,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA (32)'
        ELSE '❌ LONGITUD INCORRECTA (' || LENGTH(TWO_FACTOR_SECRET) || ')'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 5. Verificar si hay triggers que modifiquen la columna
SELECT 'VERIFICAR TRIGGERS' AS INFO FROM DUAL;
SELECT 
    TRIGGER_NAME,
    TRIGGER_TYPE,
    TRIGGERING_EVENT,
    STATUS,
    TRIGGER_BODY
FROM USER_TRIGGERS 
WHERE TABLE_NAME = 'USUARIOS'
AND (TRIGGER_BODY LIKE '%TWO_FACTOR_SECRET%' OR TRIGGER_BODY LIKE '%TWO_FACTOR%');

-- 6. Mostrar clave para Google Authenticator
SELECT 'CLAVE PARA GOOGLE AUTHENTICATOR' AS INFO FROM DUAL;
SELECT 
    'Clave: ' || TWO_FACTOR_SECRET AS CLAVE_COMPLETA,
    'Longitud: ' || LENGTH(TWO_FACTOR_SECRET) AS LONGITUD_INFO,
    'Bytes: ' || LENGTHB(TWO_FACTOR_SECRET) AS BYTES_INFO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'RECREACIÓN DE USUARIO CON CLAVE CORRECTA COMPLETADA' AS RESULTADO FROM DUAL;
