-- Script completo de diagnóstico y recuperación
-- Verificar estado actual sin modificar datos existentes
-- Ejecutar en Oracle Database

-- ==========================================
-- 1. VERIFICAR ESTRUCTURA DE TABLAS
-- ==========================================
SELECT '=== ESTRUCTURA DE TABLAS ===' AS SECCION FROM DUAL;

-- Verificar tabla USUARIOS
SELECT 'TABLA USUARIOS - COLUMNAS EXISTENTES' AS INFO FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
ORDER BY COLUMN_ID;

-- Verificar tabla PERFIL
SELECT 'TABLA PERFIL - COLUMNAS EXISTENTES' AS INFO FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PERFIL' 
ORDER BY COLUMN_ID;

-- Verificar si existe tabla USER_PAYMENT_STATUS
SELECT 'TABLA USER_PAYMENT_STATUS - EXISTENCIA' AS INFO FROM DUAL;
SELECT COUNT(*) AS EXISTE_TABLA
FROM USER_TABLES 
WHERE TABLE_NAME = 'USER_PAYMENT_STATUS';

-- ==========================================
-- 2. VERIFICAR DATOS EXISTENTES
-- ==========================================
SELECT '=== DATOS EXISTENTES ===' AS SECCION FROM DUAL;

-- Usuarios existentes
SELECT 'USUARIOS EXISTENTES' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    FECHA_ALTA,
    FECHA_MOD,
    USUARIO_MOD
FROM USUARIOS
ORDER BY NO_USUARIO;

-- Perfiles existentes
SELECT 'PERFILES EXISTENTES' AS INFO FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL,
    STATUS_PERFIL,
    FECHA_ALTA,
    FECHA_MOD,
    USUARIO_MOD
FROM PERFIL
ORDER BY ID_PERFIL;

-- ==========================================
-- 3. VERIFICAR COLUMNAS NUEVAS (SI EXISTEN)
-- ==========================================
SELECT '=== COLUMNAS NUEVAS ===' AS SECCION FROM DUAL;

-- Verificar si existen las columnas nuevas en USUARIOS
SELECT 'COLUMNAS NUEVAS EN USUARIOS' AS INFO FROM DUAL;
SELECT COLUMN_NAME
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
AND COLUMN_NAME IN ('USER_ROLE', 'PASSWORD_ENCODED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_SECRET', 'LAST_LOGIN');

-- Verificar datos en columnas nuevas (si existen)
SELECT 'DATOS EN COLUMNAS NUEVAS' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    CASE 
        WHEN COLUMN_NAME = 'USER_ROLE' THEN 'EXISTE'
        ELSE 'NO EXISTE'
    END AS USER_ROLE_STATUS,
    CASE 
        WHEN COLUMN_NAME = 'PASSWORD_ENCODED' THEN 'EXISTE'
        ELSE 'NO EXISTE'
    END AS PASSWORD_ENCODED_STATUS
FROM USUARIOS u
CROSS JOIN (
    SELECT COLUMN_NAME FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'USUARIOS' 
    AND COLUMN_NAME IN ('USER_ROLE', 'PASSWORD_ENCODED')
) cols
WHERE ROWNUM <= 1;

-- ==========================================
-- 4. VERIFICAR FUNCIONES Y PROCEDIMIENTOS
-- ==========================================
SELECT '=== FUNCIONES Y PROCEDIMIENTOS ===' AS SECCION FROM DUAL;

-- Verificar si existe la función FN_USER_HAS_ACCESS
SELECT 'FUNCIÓN FN_USER_HAS_ACCESS' AS INFO FROM DUAL;
SELECT COUNT(*) AS EXISTE_FUNCION
FROM USER_PROCEDURES 
WHERE OBJECT_NAME = 'FN_USER_HAS_ACCESS';

-- Verificar triggers
SELECT 'TRIGGERS EXISTENTES' AS INFO FROM DUAL;
SELECT TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGER_TYPE
FROM USER_TRIGGERS
ORDER BY TABLE_NAME, TRIGGER_NAME;

-- ==========================================
-- 5. VERIFICAR ÍNDICES
-- ==========================================
SELECT '=== ÍNDICES ===' AS SECCION FROM DUAL;
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_POSITION
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN ('USUARIOS', 'PERFIL', 'USER_PAYMENT_STATUS')
ORDER BY TABLE_NAME, INDEX_NAME, COLUMN_POSITION;

-- ==========================================
-- 6. VERIFICAR SINÓNIMOS
-- ==========================================
SELECT '=== SINÓNIMOS ===' AS SECCION FROM DUAL;
SELECT SYNONYM_NAME, TABLE_NAME, TABLE_OWNER
FROM USER_SYNONYMS
WHERE SYNONYM_NAME IN ('UPS', 'VUCP')
ORDER BY SYNONYM_NAME;

-- ==========================================
-- 7. VERIFICAR VISTAS
-- ==========================================
SELECT '=== VISTAS ===' AS SECCION FROM DUAL;
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS
WHERE VIEW_NAME = 'V_USUARIOS_CON_PAGO';

-- ==========================================
-- 8. RESUMEN DEL ESTADO
-- ==========================================
SELECT '=== RESUMEN DEL ESTADO ===' AS SECCION FROM DUAL;

SELECT 
    'TOTAL USUARIOS' AS METRICA,
    COUNT(*) AS VALOR
FROM USUARIOS
UNION ALL
SELECT 
    'USUARIOS ACTIVOS',
    COUNT(*)
FROM USUARIOS
WHERE ESTATUS_USUARIO = 'A'
UNION ALL
SELECT 
    'TOTAL PERFILES',
    COUNT(*)
FROM PERFIL
UNION ALL
SELECT 
    'PERFILES ACTIVOS',
    COUNT(*)
FROM PERFIL
WHERE STATUS_PERFIL = 'A'
UNION ALL
SELECT 
    'COLUMNAS NUEVAS CREADAS',
    COUNT(*)
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
AND COLUMN_NAME IN ('USER_ROLE', 'PASSWORD_ENCODED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_SECRET', 'LAST_LOGIN')
UNION ALL
SELECT 
    'TABLA PAYMENT STATUS',
    CASE WHEN COUNT(*) > 0 THEN 'EXISTE' ELSE 'NO EXISTE' END
FROM USER_TABLES 
WHERE TABLE_NAME = 'USER_PAYMENT_STATUS';

-- Script completado
SELECT '=== DIAGNÓSTICO COMPLETADO ===' AS RESULTADO FROM DUAL;
