-- Script para diagnosticar y corregir el problema de 2FA
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- DIAGNÓSTICO Y CORRECCIÓN DE 2FA
-- ==========================================

-- 1. Verificar estado actual de la clave
SELECT 'ESTADO ACTUAL DE LA CLAVE' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    TWO_FACTOR_ENABLED,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA'
        ELSE '❌ LONGITUD INCORRECTA'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 2. Verificar si hay restricciones en la columna
SELECT 'VERIFICAR RESTRICCIONES DE COLUMNA' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    CHAR_USED,
    NULLABLE
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
AND COLUMN_NAME = 'TWO_FACTOR_SECRET';

-- 3. Verificar si hay triggers que puedan estar afectando
SELECT 'VERIFICAR TRIGGERS' AS INFO FROM DUAL;
SELECT 
    TRIGGER_NAME,
    TRIGGER_TYPE,
    TRIGGERING_EVENT,
    STATUS
FROM USER_TRIGGERS 
WHERE TABLE_NAME = 'USUARIOS';

-- 4. Limpiar y reconfigurar completamente
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = NULL,
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 5. Insertar clave Base32 correcta usando método directo
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'JN7XWRTG4NVWXJTS26DUCGY8QHU',
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 6. Verificación final
SELECT 'VERIFICACIÓN FINAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_SECRET AS CLAVE_BASE32,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA (32)'
        ELSE '❌ LONGITUD INCORRECTA (' || LENGTH(TWO_FACTOR_SECRET) || ')'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 7. Mostrar clave para verificar manualmente
SELECT 'CLAVE PARA VERIFICAR MANUALMENTE' AS INFO FROM DUAL;
SELECT 
    'Clave: ' || TWO_FACTOR_SECRET AS CLAVE_COMPLETA,
    'Longitud: ' || LENGTH(TWO_FACTOR_SECRET) AS LONGITUD_INFO,
    'Caracteres: ' || LENGTHB(TWO_FACTOR_SECRET) AS BYTES_INFO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'DIAGNÓSTICO Y CORRECCIÓN COMPLETADO' AS RESULTADO FROM DUAL;
