-- Script para verificar la estructura real de la tabla PERFIL
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR ESTRUCTURA REAL DE TABLA PERFIL
-- ==========================================

SELECT '=== ESTRUCTURA REAL DE TABLA PERFIL ===' AS SECCION FROM DUAL;

-- 1. Mostrar todas las columnas de la tabla PERFIL
SELECT 'COLUMNAS EXISTENTES EN TABLA PERFIL' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE,
    DATA_DEFAULT,
    COLUMN_ID
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PERFIL' 
ORDER BY COLUMN_ID;

-- 2. Mostrar datos de la tabla PERFIL
SELECT 'DATOS EXISTENTES EN TABLA PERFIL' AS INFO FROM DUAL;
SELECT * FROM PERFIL ORDER BY ID_PERFIL;

-- 3. Verificar si existe alguna columna de estado
SELECT 'VERIFICAR COLUMNAS DE ESTADO' AS INFO FROM DUAL;
SELECT COLUMN_NAME
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PERFIL' 
AND (UPPER(COLUMN_NAME) LIKE '%STATUS%' 
     OR UPPER(COLUMN_NAME) LIKE '%ESTADO%'
     OR UPPER(COLUMN_NAME) LIKE '%ACTIVO%'
     OR UPPER(COLUMN_NAME) LIKE '%ESTATUS%');

-- 4. Verificar estructura de tabla USUARIOS también
SELECT 'COLUMNAS EXISTENTES EN TABLA USUARIOS' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE,
    COLUMN_ID
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
ORDER BY COLUMN_ID;

-- 5. Mostrar algunos datos de USUARIOS para referencia
SELECT 'DATOS DE USUARIOS (PRIMEROS 5)' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL
FROM USUARIOS
WHERE ROWNUM <= 5
ORDER BY NO_USUARIO;

-- 6. Verificar relación entre USUARIOS y PERFIL
SELECT 'RELACIÓN USUARIOS-PERFIL' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
WHERE ROWNUM <= 10
ORDER BY u.NO_USUARIO;

-- Script completado
SELECT '=== VERIFICACIÓN DE ESTRUCTURA COMPLETADA ===' AS RESULTADO FROM DUAL;
