-- Script para verificar roles anteriores existentes
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR ROLES/PERFILES ANTERIORES
-- ==========================================

SELECT '=== VERIFICACIÓN DE PERFILES/ROLES ANTERIORES ===' AS SECCION FROM DUAL;

-- 1. Mostrar todos los perfiles existentes
SELECT 'PERFILES EXISTENTES EN LA TABLA PERFIL' AS INFO FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL,
    FECHA_ALTA,
    FECHA_MOD,
    USUARIO_MOD
FROM PERFIL
ORDER BY ID_PERFIL;

-- 2. Mostrar usuarios y sus perfiles actuales
SELECT 'USUARIOS Y SUS PERFILES ACTUALES' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL,
    u.ESTATUS_USUARIO,
    CASE 
        WHEN u.USER_ROLE IS NULL THEN 'SIN ROL NUEVO'
        ELSE u.USER_ROLE
    END AS ROL_NUEVO
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
ORDER BY u.NO_USUARIO;

-- 3. Verificar si hay usuarios sin perfil asignado
SELECT 'USUARIOS SIN PERFIL ASIGNADO' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ID_PERFIL,
    u.ESTATUS_USUARIO
FROM USUARIOS u
WHERE u.ID_PERFIL IS NULL
ORDER BY u.NO_USUARIO;

-- 4. Verificar si hay perfiles sin usuarios
SELECT 'PERFILES SIN USUARIOS ASIGNADOS' AS INFO FROM DUAL;
SELECT 
    p.ID_PERFIL,
    p.NOMBRE_PERFIL,
    COUNT(u.NO_USUARIO) AS TOTAL_USUARIOS
FROM PERFIL p
LEFT JOIN USUARIOS u ON p.ID_PERFIL = u.ID_PERFIL AND u.ESTATUS_USUARIO = 'A'
GROUP BY p.ID_PERFIL, p.NOMBRE_PERFIL
ORDER BY p.ID_PERFIL;

-- 5. Mostrar estadísticas de uso de perfiles
SELECT 'ESTADÍSTICAS DE USO DE PERFILES' AS INFO FROM DUAL;
SELECT 
    p.NOMBRE_PERFIL,
    COUNT(u.NO_USUARIO) AS TOTAL_USUARIOS,
    COUNT(CASE WHEN u.ESTATUS_USUARIO = 'A' THEN 1 END) AS USUARIOS_ACTIVOS,
    COUNT(CASE WHEN u.ESTATUS_USUARIO = 'I' THEN 1 END) AS USUARIOS_INACTIVOS
FROM PERFIL p
LEFT JOIN USUARIOS u ON p.ID_PERFIL = u.ID_PERFIL
GROUP BY p.ID_PERFIL, p.NOMBRE_PERFIL
ORDER BY TOTAL_USUARIOS DESC;

-- 6. Verificar integridad de datos
SELECT 'VERIFICACIÓN DE INTEGRIDAD' AS INFO FROM DUAL;
SELECT 
    'TOTAL USUARIOS' AS METRICA,
    COUNT(*) AS VALOR
FROM USUARIOS
UNION ALL
SELECT 
    'USUARIOS CON PERFIL VÁLIDO',
    COUNT(*)
FROM USUARIOS u
INNER JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
UNION ALL
SELECT 
    'USUARIOS SIN PERFIL',
    COUNT(*)
FROM USUARIOS
WHERE ID_PERFIL IS NULL
UNION ALL
SELECT 
    'TOTAL PERFILES',
    COUNT(*)
FROM PERFIL;

-- 7. Mostrar usuarios que podrían tener problemas de acceso
SELECT 'USUARIOS CON POSIBLES PROBLEMAS DE ACCESO' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ESTATUS_USUARIO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL,
    CASE 
        WHEN u.ESTATUS_USUARIO != 'A' THEN 'USUARIO INACTIVO'
        WHEN u.ID_PERFIL IS NULL THEN 'SIN PERFIL'
        WHEN u.USER_ROLE IS NULL THEN 'SIN ROL NUEVO'
        ELSE 'OK'
    END AS PROBLEMA
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
WHERE u.ESTATUS_USUARIO != 'A' 
   OR u.ID_PERFIL IS NULL 
   OR u.USER_ROLE IS NULL
ORDER BY u.NO_USUARIO;

-- Script completado
SELECT '=== VERIFICACIÓN DE ROLES COMPLETADA ===' AS RESULTADO FROM DUAL;
