-- Script para corregir la clave Base32 con longitud exacta
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- CORRECCIÓN DE LONGITUD DE CLAVE BASE32
-- ==========================================

-- 1. Verificar estado actual
SELECT 'ESTADO ACTUAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD_ACTUAL,
    DUMP(TWO_FACTOR_SECRET) AS DUMP_INFO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 2. Limpiar y establecer clave Base32 correcta (32 caracteres exactos)
-- Usando TRIM para eliminar espacios y caracteres invisibles
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = TRIM('JN7XWRTG4NVWXJTS26DUCGY8QHU'),  -- 32 caracteres exactos
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 3. Verificar nueva configuración
SELECT 'VERIFICACIÓN POST-CORRECCIÓN' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_SECRET AS CLAVE_BASE32,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA (32)'
        WHEN LENGTH(TWO_FACTOR_SECRET) < 32 THEN '❌ MUY CORTA'
        ELSE '⚠️ MUY LARGA'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 4. Verificar que no hay caracteres invisibles
SELECT 'ANÁLISIS DE CARACTERES' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    LENGTHB(TWO_FACTOR_SECRET) AS BYTES,
    REGEXP_COUNT(TWO_FACTOR_SECRET, '[A-Z2-7]') AS CARACTERES_VALIDOS,
    CASE 
        WHEN REGEXP_COUNT(TWO_FACTOR_SECRET, '[A-Z2-7]') = 32 THEN '✅ SOLO CARACTERES BASE32'
        ELSE '❌ CONTIENE CARACTERES INVÁLIDOS'
    END AS VALIDACION_CARACTERES
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'CORRECCIÓN DE LONGITUD COMPLETADA - VERIFICAR 32 CARACTERES' AS RESULTADO FROM DUAL;
