-- Script para verificar usuarios existentes y su estado
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR USUARIOS EXISTENTES
-- ==========================================

-- 1. Verificar TODOS los usuarios (activos e inactivos)
SELECT 'TODOS LOS USUARIOS EXISTENTES' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    USER_ROLE,
    PASSWORD_ENCODED,
    FECHA_ALTA,
    FECHA_MOD
FROM USUARIOS
ORDER BY NO_USUARIO;

-- 2. Verificar usuarios activos específicamente
SELECT 'USUARIOS ACTIVOS (ESTATUS_USUARIO = A)' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    USER_ROLE
FROM USUARIOS
WHERE ESTATUS_USUARIO = 'A'
ORDER BY NO_USUARIO;

-- 3. Verificar usuarios inactivos
SELECT 'USUARIOS INACTIVOS' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    USER_ROLE
FROM USUARIOS
WHERE ESTATUS_USUARIO != 'A' OR ESTATUS_USUARIO IS NULL
ORDER BY NO_USUARIO;

-- 4. Verificar perfiles disponibles
SELECT 'PERFILES DISPONIBLES' AS INFO FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 5. Contar usuarios por estado
SELECT 'CONTEO DE USUARIOS POR ESTADO' AS INFO FROM DUAL;
SELECT 
    CASE 
        WHEN ESTATUS_USUARIO = 'A' THEN 'ACTIVO'
        WHEN ESTATUS_USUARIO = 'I' THEN 'INACTIVO'
        WHEN ESTATUS_USUARIO IS NULL THEN 'SIN ESTADO'
        ELSE 'OTRO: ' || ESTATUS_USUARIO
    END AS ESTADO,
    COUNT(*) AS TOTAL_USUARIOS
FROM USUARIOS
GROUP BY ESTATUS_USUARIO
ORDER BY ESTADO;

-- Script completado
SELECT 'VERIFICACIÓN DE USUARIOS COMPLETADA' AS RESULTADO FROM DUAL;
