-- Script definitivo para corregir la clave Base32
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- SOLUCIÓN DEFINITIVA - CLAVE BASE32
-- ==========================================

-- 1. Verificar estado actual
SELECT 'ESTADO ACTUAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    DUMP(TWO_FACTOR_SECRET) AS DUMP_INFO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 2. Eliminar completamente la clave actual
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = NULL
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 3. Insertar clave Base32 correcta usando INSERT directo
-- La clave debe ser exactamente 32 caracteres: JN7XWRTG4NVWXJTS26DUCGY8QHU
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'JN7XWRTG4NVWXJTS26DUCGY8QHU',
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 4. Verificación inmediata
SELECT 'VERIFICACIÓN INMEDIATA' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ CORRECTO (32)'
        ELSE '❌ INCORRECTO (' || LENGTH(TWO_FACTOR_SECRET) || ')'
    END AS VALIDACION
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 5. Si aún no funciona, usar función de reemplazo
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = REPLACE(REPLACE(REPLACE(TWO_FACTOR_SECRET, CHR(0), ''), CHR(32), ''), CHR(9), ''),
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 6. Verificación final
SELECT 'VERIFICACIÓN FINAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_SECRET AS CLAVE_BASE32,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    LENGTHB(TWO_FACTOR_SECRET) AS BYTES,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA (32)'
        WHEN LENGTH(TWO_FACTOR_SECRET) < 32 THEN '❌ MUY CORTA (' || LENGTH(TWO_FACTOR_SECRET) || ')'
        ELSE '⚠️ MUY LARGA (' || LENGTH(TWO_FACTOR_SECRET) || ')'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 7. Mostrar clave para copiar
SELECT 'CLAVE PARA GOOGLE AUTHENTICATOR' AS INFO FROM DUAL;
SELECT 
    'Clave: ' || TWO_FACTOR_SECRET AS CLAVE_COMPLETA,
    'Longitud: ' || LENGTH(TWO_FACTOR_SECRET) AS LONGITUD_INFO,
    'Caracteres: ' || LENGTHB(TWO_FACTOR_SECRET) AS BYTES_INFO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'CORRECCIÓN DEFINITIVA COMPLETADA' AS RESULTADO FROM DUAL;
