-- Script para verificar configuración de menús y perfiles
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR CONFIGURACIÓN DE MENÚS
-- ==========================================

-- 1. Verificar perfiles existentes
SELECT 'PERFILES EXISTENTES' AS INFO FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 2. Verificar configuración de menús
SELECT 'CONFIGURACIÓN DE MENÚS' AS INFO FROM DUAL;
SELECT 
    mc.ID_CONFIG,
    mc.ID_PERFIL,
    p.NOMBRE_PERFIL,
    mc.MENU_LABEL,
    mc.MENU_PATH,
    mc.IS_VISIBLE,
    mc.ORDEN,
    mc.FECHA_CREACION,
    mc.FECHA_MODIFICACION
FROM MENU_CONFIG mc
LEFT JOIN PERFIL p ON mc.ID_PERFIL = p.ID_PERFIL
ORDER BY mc.ID_PERFIL, mc.ORDEN;

-- 3. Verificar perfiles sin configuración de menú
SELECT 'PERFILES SIN CONFIGURACIÓN DE MENÚ' AS INFO FROM DUAL;
SELECT 
    p.ID_PERFIL,
    p.NOMBRE_PERFIL
FROM PERFIL p
LEFT JOIN MENU_CONFIG mc ON p.ID_PERFIL = mc.ID_PERFIL
WHERE mc.ID_PERFIL IS NULL
ORDER BY p.ID_PERFIL;

-- 4. Verificar configuraciones de menú sin perfil válido
SELECT 'CONFIGURACIONES SIN PERFIL VÁLIDO' AS INFO FROM DUAL;
SELECT 
    mc.ID_CONFIG,
    mc.ID_PERFIL,
    mc.MENU_LABEL,
    mc.MENU_PATH,
    mc.IS_VISIBLE,
    mc.ORDEN
FROM MENU_CONFIG mc
LEFT JOIN PERFIL p ON mc.ID_PERFIL = p.ID_PERFIL
WHERE p.ID_PERFIL IS NULL
ORDER BY mc.ID_CONFIG;

-- 5. Contar configuraciones por perfil
SELECT 'CONTEO DE CONFIGURACIONES POR PERFIL' AS INFO FROM DUAL;
SELECT 
    mc.ID_PERFIL,
    p.NOMBRE_PERFIL,
    COUNT(*) AS TOTAL_CONFIGURACIONES,
    COUNT(CASE WHEN mc.IS_VISIBLE = 1 THEN 1 END) AS VISIBLES,
    COUNT(CASE WHEN mc.IS_VISIBLE = 0 THEN 1 END) AS OCULTAS
FROM MENU_CONFIG mc
LEFT JOIN PERFIL p ON mc.ID_PERFIL = p.ID_PERFIL
GROUP BY mc.ID_PERFIL, p.NOMBRE_PERFIL
ORDER BY mc.ID_PERFIL;

-- 6. Verificar usuarios y sus perfiles asignados
SELECT 'USUARIOS Y SUS PERFILES ASIGNADOS' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL,
    u.ESTATUS_USUARIO,
    u.USER_ROLE
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
WHERE u.ESTATUS_USUARIO = 'A'
ORDER BY u.NO_USUARIO;

-- Script completado
SELECT 'VERIFICACIÓN DE CONFIGURACIÓN DE MENÚS COMPLETADA' AS RESULTADO FROM DUAL;
