-- Script simple para verificar estructura real de la base de datos
-- Ejecutar en Oracle Database

-- ==========================================
-- VERIFICAR ESTRUCTURA REAL
-- ==========================================

-- 1. Verificar estructura de tabla PERFIL
SELECT 'ESTRUCTURA DE TABLA PERFIL' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PERFIL' 
ORDER BY COLUMN_ID;

-- 2. Verificar estructura de tabla USUARIOS
SELECT 'ESTRUCTURA DE TABLA USUARIOS' AS INFO FROM DUAL;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
ORDER BY COLUMN_ID;

-- 3. Mostrar datos de PERFIL
SELECT 'DATOS DE TABLA PERFIL' AS INFO FROM DUAL;
SELECT * FROM PERFIL ORDER BY ID_PERFIL;

-- 4. Mostrar algunos usuarios
SELECT 'USUARIOS EXISTENTES (PRIMEROS 5)' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL
FROM USUARIOS
WHERE ROWNUM <= 5
ORDER BY NO_USUARIO;

-- 5. Verificar relación USUARIOS-PERFIL
SELECT 'RELACIÓN USUARIOS-PERFIL' AS INFO FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ID_PERFIL,
    p.NOMBRE_PERFIL
FROM USUARIOS u
LEFT JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
WHERE ROWNUM <= 10
ORDER BY u.NO_USUARIO;

-- Script completado
SELECT 'VERIFICACIÓN COMPLETADA' AS RESULTADO FROM DUAL;
