-- Script de verificación del sistema actual (NO MODIFICA NADA)
-- Ejecutar en Oracle Database para verificar el estado actual

-- 1. Verificar estructura de la tabla USUARIOS actual
SELECT 'ESTRUCTURA ACTUAL DE USUARIOS' AS VERIFICACION FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' 
ORDER BY COLUMN_ID;

-- 2. Verificar todos los usuarios existentes
SELECT 'USUARIOS EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    ID_PERFIL,
    LENGTH(PASSWORD) AS LONGITUD_PASSWORD,
    CASE 
        WHEN PASSWORD_ENCODED IS NULL THEN 'SIN DEFINIR'
        ELSE PASSWORD_ENCODED
    END AS ESTADO_CONTRASEÑA,
    CASE 
        WHEN USER_ROLE IS NULL THEN 'SIN DEFINIR'
        ELSE USER_ROLE
    END AS ROL_ACTUAL
FROM USUARIOS
ORDER BY NO_USUARIO;

-- 3. Verificar perfiles existentes
SELECT 'PERFILES EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    ID_PERFIL,
    NOMBRE_PERFIL,
    STATUS_PERFIL,
    DESCRIPCION_PERFIL
FROM PERFIL
ORDER BY ID_PERFIL;

-- 4. Verificar si existen las tablas nuevas
SELECT 'TABLAS NUEVAS (OPCIONALES)' AS VERIFICACION FROM DUAL;
SELECT 
    TABLE_NAME,
    'EXISTE' AS ESTADO
FROM USER_TABLES 
WHERE TABLE_NAME IN ('USER_PAYMENT_STATUS')
UNION ALL
SELECT 
    'USER_PAYMENT_STATUS' AS TABLE_NAME,
    'NO EXISTE' AS ESTADO
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM USER_TABLES WHERE TABLE_NAME = 'USER_PAYMENT_STATUS'
);

-- 5. Verificar funciones existentes
SELECT 'FUNCIONES EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    OBJECT_NAME,
    OBJECT_TYPE,
    STATUS
FROM USER_OBJECTS 
WHERE OBJECT_TYPE = 'FUNCTION'
AND OBJECT_NAME LIKE '%USER%'
ORDER BY OBJECT_NAME;

-- 6. Verificar triggers existentes
SELECT 'TRIGGERS EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    TRIGGER_NAME,
    TABLE_NAME,
    STATUS
FROM USER_TRIGGERS
ORDER BY TABLE_NAME, TRIGGER_NAME;

-- 7. Verificar índices existentes
SELECT 'ÍNDICES EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    INDEX_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    UNIQUENESS
FROM USER_IND_COLUMNS ic
JOIN USER_INDEXES i ON ic.INDEX_NAME = i.INDEX_NAME
WHERE ic.TABLE_NAME = 'USUARIOS'
ORDER BY ic.TABLE_NAME, ic.INDEX_NAME;

-- 8. Verificar vistas existentes
SELECT 'VISTAS EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    VIEW_NAME,
    STATUS
FROM USER_VIEWS
ORDER BY VIEW_NAME;

-- 9. Verificar sinónimos existentes
SELECT 'SINÓNIMOS EXISTENTES' AS VERIFICACION FROM DUAL;
SELECT 
    SYNONYM_NAME,
    TABLE_NAME,
    TABLE_OWNER
FROM USER_SYNONYMS
ORDER BY SYNONYM_NAME;

-- 10. Resumen del estado actual
SELECT 'RESUMEN DEL ESTADO ACTUAL' AS VERIFICACION FROM DUAL;
SELECT 
    'USUARIOS ACTIVOS' AS COMPONENTE,
    COUNT(*) AS CANTIDAD
FROM USUARIOS 
WHERE ESTATUS_USUARIO = 'A'
UNION ALL
SELECT 
    'PERFILES ACTIVOS' AS COMPONENTE,
    COUNT(*) AS CANTIDAD
FROM PERFIL 
WHERE STATUS_PERFIL = 'A'
UNION ALL
SELECT 
    'TABLAS NUEVAS' AS COMPONENTE,
    COUNT(*) AS CANTIDAD
FROM USER_TABLES 
WHERE TABLE_NAME IN ('USER_PAYMENT_STATUS')
UNION ALL
SELECT 
    'FUNCIONES NUEVAS' AS COMPONENTE,
    COUNT(*) AS CANTIDAD
FROM USER_OBJECTS 
WHERE OBJECT_TYPE = 'FUNCTION'
AND OBJECT_NAME LIKE '%USER%';

-- Script completado - NO SE MODIFICÓ NADA
SELECT 'VERIFICACIÓN COMPLETADA - SISTEMA SIN MODIFICAR' AS RESULTADO FROM DUAL;
