-- Script de prueba para verificar autenticación
-- Ejecutar en Oracle Database

-- 1. Verificar que el usuario SUPERADMIN existe y está activo
SELECT 'VERIFICACIÓN USUARIO SUPERADMIN' AS PRUEBA FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    ESTATUS_USUARIO,
    USER_ROLE,
    PASSWORD_ENCODED,
    LENGTH(PASSWORD) AS LONGITUD_PASSWORD
FROM USUARIOS 
WHERE NO_USUARIO = 'SUPERADMIN';

-- 2. Verificar estado de pago del SUPERADMIN
SELECT 'VERIFICACIÓN ESTADO DE PAGO SUPERADMIN' AS PRUEBA FROM DUAL;
SELECT 
    NO_USUARIO,
    PAYMENT_STATUS,
    CREATED_AT
FROM USER_PAYMENT_STATUS 
WHERE NO_USUARIO = 'SUPERADMIN';

-- 3. Probar función de acceso
SELECT 'PRUEBA FUNCIÓN DE ACCESO' AS PRUEBA FROM DUAL;
SELECT 
    FN_USER_HAS_ACCESS('SUPERADMIN') AS SUPERADMIN_TIENE_ACCESO
FROM DUAL;

-- 4. Verificar contraseña del SUPERADMIN (solo mostrar si es texto plano)
SELECT 'VERIFICACIÓN CONTRASEÑA SUPERADMIN' AS PRUEBA FROM DUAL;
SELECT 
    NO_USUARIO,
    CASE 
        WHEN PASSWORD_ENCODED = 'N' THEN 'TEXTO_PLANO'
        WHEN PASSWORD_ENCODED = 'Y' THEN 'CODIFICADA'
        ELSE 'DESCONOCIDO'
    END AS TIPO_CONTRASEÑA,
    CASE 
        WHEN PASSWORD_ENCODED = 'N' THEN PASSWORD
        ELSE '[CODIFICADA]'
    END AS CONTRASEÑA_VISIBLE
FROM USUARIOS 
WHERE NO_USUARIO = 'SUPERADMIN';

-- 5. Verificar todos los usuarios activos
SELECT 'TODOS LOS USUARIOS ACTIVOS' AS PRUEBA FROM DUAL;
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    u.ESTATUS_USUARIO,
    u.USER_ROLE,
    ups.PAYMENT_STATUS,
    FN_USER_HAS_ACCESS(u.NO_USUARIO) AS TIENE_ACCESO
FROM USUARIOS u
LEFT JOIN USER_PAYMENT_STATUS ups ON u.NO_USUARIO = ups.NO_USUARIO
WHERE u.ESTATUS_USUARIO = 'A'
ORDER BY u.NO_USUARIO;

-- Script completado
SELECT 'PRUEBAS COMPLETADAS' AS RESULTADO FROM DUAL;
