-- Script alternativo con clave Base32 diferente
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- CLAVE BASE32 ALTERNATIVA (32 CARACTERES)
-- ==========================================

-- 1. Limpiar completamente
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = NULL,
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 2. Usar una clave Base32 diferente (32 caracteres exactos)
-- Esta clave es: ABCDEFGHIJKLMNOPQRSTUVWXYZ234567
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 3. Verificación
SELECT 'VERIFICACIÓN CLAVE ALTERNATIVA' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ CORRECTO (32)'
        ELSE '❌ INCORRECTO (' || LENGTH(TWO_FACTOR_SECRET) || ')'
    END AS VALIDACION
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 4. Si funciona, usar la clave original
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'JN7XWRTG4NVWXJTS26DUCGY8QHU',
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A'
AND LENGTH('JN7XWRTG4NVWXJTS26DUCGY8QHU') = 32;

-- 5. Verificación final
SELECT 'VERIFICACIÓN FINAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    TWO_FACTOR_SECRET,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA'
        ELSE '❌ LONGITUD INCORRECTA'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'CLAVE ALTERNATIVA CONFIGURADA' AS RESULTADO FROM DUAL;
