-- Script alternativo para clave Base32 con verificación completa
-- Ejecutar en Oracle SQL Developer

-- ==========================================
-- CLAVE BASE32 ALTERNATIVA (32 CARACTERES)
-- ==========================================

-- 1. Eliminar completamente la clave actual
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = NULL,
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 2. Insertar clave Base32 correcta usando función de concatenación
UPDATE USUARIOS 
SET TWO_FACTOR_SECRET = 'JN7X' || 'WRTG' || '4NVW' || 'XJTS' || '26DU' || 'CGY8' || 'QHU',
    TWO_FACTOR_ENABLED = 'N'
WHERE NO_USUARIO = 'admin'
AND ESTATUS_USUARIO = 'A';

-- 3. Verificación completa
SELECT 'VERIFICACIÓN FINAL' AS INFO FROM DUAL;
SELECT 
    NO_USUARIO,
    NOMBRE_EMPLEADO,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_SECRET AS CLAVE_BASE32,
    LENGTH(TWO_FACTOR_SECRET) AS LONGITUD,
    LENGTHB(TWO_FACTOR_SECRET) AS BYTES,
    CASE 
        WHEN LENGTH(TWO_FACTOR_SECRET) = 32 THEN '✅ LONGITUD CORRECTA'
        ELSE '❌ LONGITUD INCORRECTA'
    END AS VALIDACION_LONGITUD,
    CASE 
        WHEN REGEXP_LIKE(TWO_FACTOR_SECRET, '^[A-Z2-7]{32}$') THEN '✅ FORMATO BASE32 VÁLIDO'
        ELSE '❌ FORMATO INVÁLIDO'
    END AS VALIDACION_FORMATO,
    CASE 
        WHEN TWO_FACTOR_ENABLED = 'Y' THEN '✅ 2FA ACTIVO'
        WHEN TWO_FACTOR_ENABLED = 'N' AND TWO_FACTOR_SECRET IS NOT NULL THEN '⚙️ PENDIENTE DE ACTIVAR'
        ELSE '❌ 2FA NO CONFIGURADO'
    END AS ESTADO_2FA
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

-- 4. Mostrar clave para copiar manualmente
SELECT 'CLAVE PARA GOOGLE AUTHENTICATOR' AS INFO FROM DUAL;
SELECT 
    'Clave: ' || TWO_FACTOR_SECRET AS CLAVE_COMPLETA,
    'Longitud: ' || LENGTH(TWO_FACTOR_SECRET) AS LONGITUD_INFO
FROM USUARIOS
WHERE NO_USUARIO = 'admin';

COMMIT;

-- Script completado
SELECT 'CLAVE BASE32 CORREGIDA - LISTA PARA GOOGLE AUTHENTICATOR' AS RESULTADO FROM DUAL;
