-- Script para verificar el estado actual de la configuración de menús

-- 1. Verificar configuración de pestañas principales
SELECT 
    mc.ID_CONFIG,
    mc.ID_PERFIL,
    p.NOMBRE_PERFIL,
    mc.MENU_LABEL,
    mc.MENU_PATH,
    mc.IS_VISIBLE,
    mc.ORDEN,
    mc.USUARIO_CREACION,
    mc.FECHA_CREACION
FROM MENU_CONFIG mc
JOIN PERFIL p ON mc.ID_PERFIL = p.ID_PERFIL
WHERE mc.MENU_PATH IS NULL
ORDER BY mc.ID_PERFIL, mc.ORDEN;

-- 2. Verificar configuración de pantallas específicas
SELECT 
    mc.ID_CONFIG,
    mc.ID_PERFIL,
    p.NOMBRE_PERFIL,
    mc.MENU_LABEL,
    mc.MENU_PATH,
    mc.IS_VISIBLE,
    mc.ORDEN,
    mc.USUARIO_CREACION,
    mc.FECHA_CREACION
FROM MENU_CONFIG mc
JOIN PERFIL p ON mc.ID_PERFIL = p.ID_PERFIL
WHERE mc.MENU_PATH IS NOT NULL
ORDER BY mc.ID_PERFIL, mc.ORDEN;

-- 3. Contar configuraciones por perfil
SELECT 
    p.NOMBRE_PERFIL,
    COUNT(CASE WHEN mc.MENU_PATH IS NULL THEN 1 END) as PESTANAS_PRINCIPALES,
    COUNT(CASE WHEN mc.MENU_PATH IS NOT NULL THEN 1 END) as PANTALLAS_ESPECIFICAS,
    COUNT(CASE WHEN mc.IS_VISIBLE = 1 AND mc.MENU_PATH IS NULL THEN 1 END) as PESTANAS_VISIBLES,
    COUNT(CASE WHEN mc.IS_VISIBLE = 1 AND mc.MENU_PATH IS NOT NULL THEN 1 END) as PANTALLAS_VISIBLES
FROM PERFIL p
LEFT JOIN MENU_CONFIG mc ON p.ID_PERFIL = mc.ID_PERFIL
GROUP BY p.ID_PERFIL, p.NOMBRE_PERFIL
ORDER BY p.ID_PERFIL;

-- 4. Verificar usuarios y sus perfiles
SELECT 
    u.NO_USUARIO,
    u.NOMBRE_EMPLEADO,
    p.NOMBRE_PERFIL,
    u.ESTATUS_USUARIO
FROM USUARIOS u
JOIN PERFIL p ON u.ID_PERFIL = p.ID_PERFIL
ORDER BY u.ID_PERFIL, u.NO_USUARIO;
